#!/bin/bash

trap "clear" EXIT

HOST_LIST=()
while read -r line; do
    if [[ -n "$line" ]] && [[ "$line" != "Host " ]]; then
        HOST_LIST+=($line "")
    fi
done <<< $(grep -Poh "(?<=^Host\s)[\w._-]*$" ~/.ssh/config)

if [ ${#HOST_LIST[@]} -eq 0 ]; then
    echo "Error: No SSH hosts found in configuration file"
    exit 1
fi

HEIGHT=20
WIDTH=60
BACKTITLE="Select you SSH connection"
TITLE="SSH Servers"
MENU="Choose one of the following servers:"

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $HEIGHT \
                "${HOST_LIST[@]}" \
                2>&1 >/dev/tty)
clear

ssh $CHOICE
