#!/bin/bash

trap "clear" EXIT

HOST_LIST=()
while read -r line; do
    HOST_LIST+=($line "")
done <<< $(grep -Poh "(?<=^Host\s)[\w._-]*$" ~/.ssh/config)

HEIGHT=15
WIDTH=50
BACKTITLE="Select you SSH connection"
TITLE="SSH Servers"
MENU="Choose one of the following servers:"

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $HEIGHT \
                "${HOST_LIST[@]}" \
                2>&1 >/dev/tty)
clear

ssh $CHOICE
